version: '3.9'

services:
  python_job:
    image: python:slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    command: sh -c "pip install -r requirements.txt && python -u main.py"
    networks:
      - data

networks:
  data:
    name: data
    external: true